### ISSUE TITLE
Invalid Place Types

### ISSUE THREAD

**Issue by JailbirdInteractive** [nomanr/Android-Google-Places-API#1]
Hey, I just started using your library and it works really well but some of the PlaceTypes keep saying they're invalid even though I see them listed in the PlaceType class. Do you know why that is?

**Comment by nomanr** [comment]
Hey, I am not sure. Can you share the code snippet where you are using the library ?

**Comment by JailbirdInteractive** [comment]
I'm just using it exactly as it is in the example with PlaceType.CARD_DEALER as the type.

**Comment by nomanr** [comment]
Right, there are a few typos. Will fix those. Thanks

**Comment by nomanr** [comment]
Fixed in `1.1.2`
