### ISSUE TITLE
Crashes when using the .language parameter

### ISSUE THREAD

**Issue by spatrickapps** [nomanr/Android-Google-Places-API#2]
whenever i use `.language("es")` it crashes my app. Everything else works fine.

**Comment by nomanr** [comment]
hi can you post the crash log?

**Comment by spatrickapps** [comment]
this is all i got

`12-07 12:29:20.406 1593-2512/? W/InputDispatcher: Attempted to unregister already unregistered input channel '9d4eae40 com.myapp.project/com.myapp.project.MainActivity (server)'
12-07 12:29:20.406 1593-1782/? I/ActivityManager: Process com.myapp.project (pid 8374) has died.
12-07 12:29:20.406 1593-2512/? I/WindowState: WIN DEATH: Window{9d4eae40 u0 com.myapp.project/com.myapp.project.MainActivity}
12-07 12:29:20.406 1593-1782/? W/ActivityManager: Force removing ActivityRecord{9d49a5a0 u0 com.myapp.project/.MainActivity t35}: app died, no saved state
12-07 12:29:20.506 1704-1716/? W/Binder: Caught a RuntimeException from the binder stub implementation.
                                         java.lang.NullPointerException
                                             at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
                                             at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
                                             at android.os.Binder.execTransact(Binder.java:404)
                                             at dalvik.system.NativeStart.run(Native Method)
12-07 12:29:20.506 1593-1782/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 8374 uid 10074`

**Comment by spatrickapps** [comment]
Does the language parameter work for you?

**Comment by nomanr** [comment]
Yes it worked. Well I can tell from log that it doesn't have anything to do with the library but something's up with your app logic.

**Comment by spatrickapps** [comment]
I found the error message
`Caused by: java.lang.IllegalArgumentException: Invalid language code`

**Comment by spatrickapps** [comment]
It only happens when i use `.language("es")`

**Comment by nomanr** [comment]
Try version `1.1.3`
